services:
  - type: web
    name: nutricalc-api
    env: python
    buildCommand: "./build.sh"
    startCommand: "cd nutri_calc && gunicorn nutri_calc.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.2
