# Generated by Django 6.0.3 on 2026-03-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('meat', '🥩 Meat & Poultry'), ('seafood', '🐟 Seafood'), ('dairy', '🥛 Dairy & Eggs'), ('grain', '🌾 Grains & Cereals'), ('vegetable', '🥦 Vegetables'), ('fruit', '🍎 Fruits'), ('legume', '🫘 Legumes & Beans'), ('nut', '🥜 Nuts & Seeds'), ('oil', '🫙 Oils & Fats'), ('sweetener', '🍯 Sweeteners'), ('beverage', '☕ Beverages'), ('condiment', '🧂 Condiments & Spices'), ('other', '🍽️ Other')], default='other', max_length=20)),
                ('calories_per_100g', models.FloatField(help_text='kcal per 100g')),
                ('protein_g', models.FloatField(default=0.0, help_text='Protein in grams per 100g')),
                ('carbs_g', models.FloatField(default=0.0, help_text='Carbohydrates in grams per 100g')),
                ('fat_g', models.FloatField(default=0.0, help_text='Fat in grams per 100g')),
                ('fiber_g', models.FloatField(default=0.0, help_text='Fiber in grams per 100g')),
                ('sugar_g', models.FloatField(default=0.0, help_text='Sugar in grams per 100g')),
                ('sodium_mg', models.FloatField(default=0.0, help_text='Sodium in mg per 100g')),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
